export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_AMOUNT = "INCREASE_AMOUNT";
export const DECREASE_AMOUNT = "DECREASE_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

